version: '3.8'

services:
  # Production service
  tony-wallet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
